from urllib.parse import unquote
import base64
import json
import requests

from slack_block_kits import get_main_menu_blocks


def base64_encoder(body):
    decoded_data = unquote(base64.b64decode(body))

    # parse body when event was generated by command '/start'
    if decoded_data.startswith('token'):
        items_list = list()
        for item in decoded_data.split('&'):
            item = tuple(item.split('='))
            items_list.append(item)
        body = dict(items_list)

        return body

    # parse body when event was generated by clicking on the button or by submitting modal
    elif decoded_data.startswith('payload'):
        body = json.loads(decoded_data.split('=', 1)[1])

        return body


def respond_with_menu(response_url):
    data = {
        'response_type': 'in_channel',
        "blocks": get_main_menu_blocks()
    }

    headers = {
        'Content-type': 'application/json'
    }

    requests.post(response_url, data=json.dumps(data), headers=headers)


def respond_with_error_return_menu(response_url):
    data = {
        'response_type': 'in_channel',
        "text": "Something went wrong. Please try again.",
        "blocks": get_main_menu_blocks()
    }

    headers = {
        'Content-type': 'application/json'
    }

    requests.post(response_url, data=json.dumps(data), headers=headers)
