"""alter RequestHistory table

Revision ID: 142b625bdce3
Revises: 5755bde987c5
Create Date: 2022-07-25 00:06:27.723714

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '142b625bdce3'
down_revision = '5755bde987c5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requests_history', sa.Column('changes', sa.String(length=200), nullable=False))
    op.add_column('requests_history', sa.Column('editor', sa.String(length=50), nullable=False))
    op.drop_column('requests_history', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requests_history', sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.drop_column('requests_history', 'editor')
    op.drop_column('requests_history', 'changes')
    # ### end Alembic commands ###
