"""Add RequestHistory table

Revision ID: 8cc2b09e8957
Revises: e77b8e3d2b31
Create Date: 2022-07-16 00:20:06.978350

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8cc2b09e8957'
down_revision = 'e77b8e3d2b31'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creator', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=100), nullable=False),
    sa.Column('reviewer', sa.Integer(), nullable=True),
    sa.Column('type_bonus', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payment_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['creator'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reviewer'], ['users.id'], ),
    sa.ForeignKeyConstraint(['type_bonus'], ['type_bonus.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('requests_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=100), nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('request_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['request_id'], ['requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('request')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('request',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('creator', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('reviewer', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('type_bonus', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('payment_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['creator'], ['users.id'], name='request_creator_fkey'),
    sa.ForeignKeyConstraint(['reviewer'], ['users.id'], name='request_reviewer_fkey'),
    sa.ForeignKeyConstraint(['type_bonus'], ['type_bonus.id'], name='request_type_bonus_fkey'),
    sa.PrimaryKeyConstraint('id', name='request_pkey')
    )
    op.drop_table('requests_history')
    op.drop_table('requests')
    # ### end Alembic commands ###
