"""Change columns types

Revision ID: a005336b297b
Revises: e58c16a4487a
Create Date: 2022-07-21 12:01:54.740957

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a005336b297b'
down_revision = 'e58c16a4487a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
